# Generated by Django 2.2 on 2019-11-16 04:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon_id', models.IntegerField()),
                ('kingdom', models.CharField(blank=True, max_length=100, null=True)),
                ('scientific_name', models.CharField(max_length=100)),
                ('appendix', models.CharField(max_length=5)),
                ('author', models.CharField(max_length=100)),
                ('country_distribution', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None), size=None)),
                ('distribution_iso_codes', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=None), size=None)),
            ],
        ),
    ]
