# Generated by Django 2.2 on 2019-11-16 09:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonconcept',
            name='country_distribution',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='taxonconcept',
            name='distribution_iso_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, size=None),
        ),
    ]
